USE [DBSK002]
GO

--DROP TABLE TB_ENDERECOS
--DROP TABLE TB_CONTATOS
--DROP TABLE Tb_FUNCIONARIOS
--DROP TABLE DBSK001..Tb_CLASSES
CREATE TABLE Tb_Classes(
	COD       int identity(1,1) NOT NULL,
	CLASSE    varchar(20)       NOT NULL,
	DESCRICAO varchar(100)      NOT NULL,
	ATIVO     int               NOT NULL
)



