USE [DBSK002]
GO

/****** Object:  Table [dbo].[TB_PERSONAGENS]    Script Date: 27/11/2020 12:29:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--DROP TABLE DBSK002..TB_ATRIBUTOS
CREATE TABLE DBSK002..TB_ATRIBUTOS(
	 COD             int IDENTITY(1,1) NOT NULL,
	 FORC            int               NOT NULL,
	 DEST            int               NOT NULL,
	 CONS            int               NOT NULL,
	 INTE            int               NOT NULL,
	 SABE            int               NOT NULL,
	 CARI            int               NOT NULL,
	 DataAtualizacao varchar(20)       NOT NULL,
	 COD_PERSONAGEM  int               NOT NULL,
	 ATIVO           int               NOT NULL,
 CONSTRAINT PK_COD_ATRIBUTOS PRIMARY KEY CLUSTERED 
(COD ASC) WITH 
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [dbo].TB_ATRIBUTOS  WITH CHECK ADD  CONSTRAINT [FK_COD_PERSONAGEM_ATRIBUTOS] FOREIGN KEY(COD_PERSONAGEM)
REFERENCES [dbo].TB_PERSONAGENS ([COD])
GO

ALTER TABLE [dbo].TB_ATRIBUTOS CHECK CONSTRAINT [FK_COD_PERSONAGEM_ATRIBUTOS]
GO

--CREATE UNIQUE INDEX index_LOGIN
-- ON Tb_Usuarios (LOGIN);

