USE DBSK002

SELECT * FROM DBSK002..TB_USUARIOS

SELECT * FROM DBSK002..TB_RACAS

SELECT * FROM DBSK002..Tb_Classes

SELECT * FROM DBSK002..TB_CAMPANHAS

SELECT * FROM DBSK002..TB_JOGADORES

SELECT * FROM DBSK002..TB_PERSONAGENS

SELECT * FROM DBSK002..TB_ATRIBUTOS

SELECT * FROM DBSK002..TB_SKILLS

SELECT * FROM DBSK002..TB_ITENS

SELECT * FROM DBSK002..Tb_TipoItens

SELECT U.COD,U.LOGIN from DBSK002..TB_USUARIOS as U
INNER JOIN DBSK002..TB_JOGADORES as J 
on U.COD = J.COD_USUARIO
where U.ATIVO = 1

--SELECT EM 3 TABELAS
--select P.COD,P.NOME,RACA,CLASSE,ALINHAMENTO,NIVEL,J.NOME as 'JOGADOR',C.NOMECAMPANHA  FROM TB_PERSONAGENS as P
--INNER JOIN TB_JOGADORES as J ON P.COD_JOGADOR = J.COD
--INNER JOIN TB_CAMPANHAS as C ON C.COD = P.COD_CAMPANHA

Select P.COD,NOME,RACA,CLASSE,ALINHAMENTO,CA,PVTOTAL,PVATUAL,PATAQUE,INICIATIVA,NIVEL,A.FORC,A.DEST,A.CONS,A.INTE,A.SABE,A.CARI,HISTORIA 
From TB_PERSONAGENS as P
INNER JOIN TB_ATRIBUTOS as A on A.COD_PERSONAGEM = P.COD
WHERE P.ATIVO = 1 and COD_CAMPANHA = 1 ORDER BY INICIATIVA DESC